### ISSUE TITLE
logging verbosity

### ISSUE THREAD

**Issue by mikapfl** [primap-community/primap2#209]
At the moment, our logging is active by default and very verbose (prints all debug messages). Maybe we should change that. I find myself disabling most logging usually if I write some script.

loguru recommends that libraries should by default disable their loggers completely to not annoy users of libraries, then users enable the loggers selectively. But maybe that's also a bit annoying?

I'm not quite sure what we should do, but maybe enable logging by default at the `info` level? @JGuetschow opinions?

**Comment by JGuetschow** [comment]
Currently default logging is a bit too much for production code, I think. I think reducing it would be good.
