### ISSUE TITLE
Harmonize parameter naming for selections/filters

### ISSUE THREAD

**Issue by JGuetschow** [primap-community/primap2#244]
**Is your feature request related to a problem? Please describe.**

Parameters to limit functions to a selection of the dataset use different names. In the downscaling function we use `sel` and in the aggregation functions we use `filter` 

**Describe the solution you'd like**

Parameters that fulfill the same purpose should have the same name so users don't have to remerber different names for different functions.

**Additional context**

We've not used the new aggregation functions a lot, so it should be acceptable work to change the parameter name for these functions and adapt the code that already uses the functions.

**Comment by mikapfl** [comment]
I agree, it would be great to have a self-consistent API. We could also support the old name `filter` for legacy compatibility, but document that it is better to use `sel` instead.
